### ISSUE TITLE
Docker compose fails if  `.motion` directory is not present

### ISSUE THREAD

**Issue by masih** [filecoin-project/motion-s3-connector#8]
On running the s3 connector docker compose, by default it uses `$HOME/.motion` folder on host. If the `.motion` directory is not present then `docker compose up` fails.

Update README to instruct users to create `.motion` folder if the `MOTION_HOME` environment variable is not set.

**Comment by elijaharita** [comment]
even if MOTION_HOME is set, it still fails if the directory has not been manually created

does it not make sense to just initialize an empty directory in this case?

**Comment by masih** [comment]
> to just initialize an empty directory in this case?

Sure, let's do that.

Looking at the docker compose file i don't see why even after overriding `MOTION_HOME` to a directory that does exist the error would happen. We can take a closer look at it later. For now my vote would be to update the README and concentrate on multi-part upload support :)
